version: '3'
services:
  app:
    container_name: openai-node-proxy
    image: harbor.batman.video:9090/video/openai-node-proxy:1.0.0
    restart: always
    build: .
    ports:
      - '8090:8090'
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY